version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/node:carbon
    working_directory: ~/cachimo
    steps:
      - checkout
      - run: yarn install
      - run: yarn run lint
      - run: yarn test
